defaults: &defaults
  resource_class: small
  working_directory: ~/easy-vcard
  docker:
    - image: cimg/node:16.20

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/easy-vcard
      - checkout
      - run:
          name: install node modules
          command: npm install --unsafe-perm=true --no-save
      - run:
          name: test easy-vcard
          command: npm run test:ci
      - store_test_results:
          path: ~/xapp/test_results
      - run:
          name: build easy-vcard
          command: npm run build